services:
  server:
    container_name: PRM-Server
    hostname: prm-server
    restart: unless-stopped
    build: 
      dockerfile: server/Dockerfile
    ports:
      - 3001:3001
    env_file:
      - .env
  database:
    hostname: postgres
    container_name: PRM-Postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.1
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432