services:
  server:
    container_name: PRM-Server
    hostname: prm-server
    restart: unless-stopped
    build: 
      dockerfile: server/Dockerfile
      target: dev
    ports:
      - 3001:3001
      - 5000:9230
    volumes:
      - ./server:/usr/src/app
      - ./open-api:/usr/src/open-api
      - /usr/src/app/node_modules
    env_file:
      - .env
  web:
    container_name: PRM-Web
    restart: unless-stopped
    build:
      context: web
    command: ['/usr/src/app/web/bin/prm-web']
    env_file:
      - .env
    ports:
      - 2323:3000
    environment:
      - SERVER_URL=http://prm-server:3001
    volumes:
      - ./web:/usr/src/app/web
      - ./open-api/:/usr/src/app/open-api/
      - /usr/src/app/web/node_modules
  database:
    hostname: postgres
    container_name: PRM-Postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.1
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432