"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const users_1 = require("../../controllers/users");
const checkJwt_1 = require("../../middleware/checkJwt");
const checkRole_1 = require("../../middleware/checkRole");
const users_2 = require("../../middleware/validation/users");
const router = (0, express_1.Router)();
router.get('/', [checkJwt_1.checkJwt, (0, checkRole_1.checkRole)(['ADMINISTRATOR'])], users_1.list);
router.get('/:id([0-9]+)', [checkJwt_1.checkJwt, (0, checkRole_1.checkRole)(['ADMINISTRATOR'], true)], users_1.show);
router.patch('/:id([0-9]+)', [checkJwt_1.checkJwt, (0, checkRole_1.checkRole)(['ADMINISTRATOR'], true), users_2.validatorEdit], users_1.edit);
router.delete('/:id([0-9]+)', [checkJwt_1.checkJwt, (0, checkRole_1.checkRole)(['ADMINISTRATOR'], true)], users_1.destroy);
exports.default = router;
